name: Test Atlas perl modules

on: [pull_request]

jobs:
  setup:
    name: ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2

      - name: Checkout config repo
        uses: actions/checkout@v2
        with:
          repository: ebi-gene-expression-group/metadata-validation-config
          path: config

      - name: Add workspace to path
        run: |
          echo "${GITHUB_WORKSPACE}" >> $GITHUB_PATH
          echo "${GITHUB_WORKSPACE}/tests" >> $GITHUB_PATH

      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ matrix.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles('test-environment.yml') }}
    
      # We use conda to install magetab-curation-scripts, which will also
      # install perl-atlas-modules and grab all the dependencies for us. Then
      # we just copy the perl modules and supporting files to overwrite the
      # installed ones for testing of the current codebase.  
      
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          environment-file: test-environment.yml
          python-version: 3.6
          channels: conda-forge,bioconda,defaults,ebi-gene-expression-group
          allow-softlinks: true
          channel-priority: flexible
          show-channel-urls: true
          use-only-tar-bz2: true
        
      - shell: bash -l {0}
        run: |
          rm -rf ${CONDA_PREFIX}/atlasprod/perl_modules
          cp -r perl_modules ${CONDA_PREFIX}/atlasprod       
          rm -rf ${CONDA_PREFIX}/atlasprod/supporting_files
          cp -r supporting_files ${CONDA_PREFIX}/atlasprod       

      - name: Run tests
        env:
          FASTQ_FILE_REPORT: 'http://ftp.ebi.ac.uk/pub/databases/ena/report/fastqFileReport.gz'
        run: |
          run-tests.sh
